# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: swift
xcode_project: _Pods.xcodeproj
xcode_scheme: GPXKit
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone XS
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
-  xcodebuild -workspace Example/GPXKit.xcworkspace -scheme GPXKit -sdk iphonesimulator12.1 -destination 'OS=12.1,name=iPhone XS'
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/GPXKit.xcworkspace -scheme GPXKit-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
